# Generated by Django 5.0.4 on 2024-04-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctor_gender_doctor_license_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile_pic',
            field=models.ImageField(upload_to='media/profile_pic/DoctorProfilePic/'),
        ),
    ]
